### ISSUE TITLE
xarray mapplot tool new version 0.20.2 doesnt seems to work properly as 0.18 is ok

### ISSUE THREAD

**Issue by yvanlebras** [galaxyecology/tools-ecology#56]
It seems the 0.20.2 last version of xarray mapplot tool the https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/xarray_mapplot/0.18.2+galaxy0 is not working properly.

Command Line
```
mkdir output_dir && mkdir -p `pwd`/mlp_tmpdir && MPLCONFIGDIR=`pwd`/mlp_tmpdir && echo "Galaxy xarray version 0.20.2" > /data/jwd/main/047/229/47229418/outputs/galaxy_dataset_bcea2075-2f6b-435d-9fbf-e34b093ef2fc.dat && python '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/dc05bf0af58f/xarray_mapplot/xarray_mapplot.py' '/data/dnb02/galaxy_db/files/020/110/dataset_20110467.dat' 'nh4' --config '/data/jwd/main/047/229/47229418/configs/tmp99x1aueb' --proj '/data/jwd/main/047/229/47229418/configs/tmpnk2bkrsk' --output plot.png --verbose && mv *.png output_dir
```

stderr
```
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/dc05bf0af58f/xarray_mapplot/xarray_mapplot.py", line 400, in <module>
    dset = MapPlotXr(input=args.input, varname=args.varname,
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/dc05bf0af58f/xarray_mapplot/xarray_mapplot.py", line 86, in __init__
    f.read().replace("\n", "").split('{')[1].split('}')[0]
IndexError: list index out of range

Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/dc05bf0af58f/xarray_mapplot/xarray_mapplot.py", line 400, in <module>
    dset = MapPlotXr(input=args.input, varname=args.varname,
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/dc05bf0af58f/xarray_mapplot/xarray_mapplot.py", line 86, in __init__
    f.read().replace("\n", "").split('{')[1].split('}')[0]
IndexError: list index out of range
rm: cannot remove '/data/jwd/main/047/229/47229418/tmp/out.1468666': No such file or directory
rm: cannot remove '/data/jwd/main/047/229/47229418/tmp/err.1468666': No such file or directory
```

Here an history where I tried to re-run the new version exactly with same parameters and input files as the 0.18 version and where I have this stderr mentionned before.

Any idea @annefou ?

**Comment by yvanlebras** [comment]
hmmm comparing the command lines, it seems there is some lacking information....

For example latitude and longitude infos..

Here is the 0.18 command line:
```
mkdir output_dir && mkdir -p `pwd`/mlp_tmpdir && MPLCONFIGDIR=`pwd`/mlp_tmpdir && echo "Galaxy xarray version 0.18.2" > /data/jwd/main/047/205/47205078/outputs/galaxy_dataset_b645594e-35f9-43b2-babe-c5ab2ed59fe7.dat && python '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ecology/xarray_mapplot/d7479b6dfbe8/xarray_mapplot/xarray_mapplot.py' '/data/dnb02/galaxy_db/files/020/110/dataset_20110467.dat' 'nh4' --time="19" --latitude='latitude' --longitude='longitude' --cmap='coolwarm' --output plot.png --verbose && mv *.png output_dir
```

**Comment by annefou** [comment]
The two versions are not "compatible". To fix a few bugs (such as having a title, etc.), I moved all the information into a config file.
